Update patch set 3
Patch Set 3:

Tests failed with

paladox@gerrit-test:~/gerrit$ bazel build plugins/evict-cache:evict_cache_tests
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.build/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
INFO: Found 1 target...
ERROR: /home/paladox/gerrit/plugins/evict-cache/BUILD:26:1: Java compilation in rule '//plugins/evict-cache:evict_cache_tests' failed: Worker process sent response with exit code: 1.
bazel-out/local-fastbuild/bin/plugins/evict-cache/evict_cache_testsTestSuite.java:5: error: Constants is not public in com.ericsson.gerrit.plugins.evictcache; cannot be accessed from outside package
@Suite.SuiteClasses({com.ericsson.gerrit.plugins.evictcache.CacheResponseHandlerTest.class,com.ericsson.gerrit.plugins.evictcache.ConfigurationTest.class,com.ericsson.gerrit.plugins.evictcache.Constants.class,com.ericsson.gerrit.plugins.evictcache.ContextTest.class,com.ericsson.gerrit.plugins.evictcache.EvictCacheExecutorProviderTest.class,com.ericsson.gerrit.plugins.evictcache.EvictCacheIT.class,com.ericsson.gerrit.plugins.evictcache.EvictCacheRestApiServletTest.class,com.ericsson.gerrit.plugins.evictcache.GsonParserTest.class,com.ericsson.gerrit.plugins.evictcache.HttpClientProviderTest.class,com.ericsson.gerrit.plugins.evictcache.HttpSessionTest.class,com.ericsson.gerrit.plugins.evictcache.ModuleTest.class,com.ericsson.gerrit.plugins.evictcache.RestSessionTest.class})
                                                                                                                                                                Target //plugins/evict-cache:evict_cache_tests failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 21.828s, Critical Path: 7.56s

Not sure how to fix that but i doint think this is caused by this patch.

Patch-set: 3
Reviewer: Paladox none <1029953@173816e5-2b9a-37c3-8a2e-48639d4f1153>